# Site title and subtitle. This is used in _includes/header.html
title: 'karyoploteR Tutorial'
subtitle: 'Tutorial and Examples on plotting genomes with karyoploteR'

# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: ''

# if you use google analytics, add your tracking id here
google_analytics_id: 'UA-98092676-1'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 2

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/bernatgel/karyoploter_tutorial'

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/karyoploter_tutorial'

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: rouge

# Since these are pages, it doesn't really matter
future: true

# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the kramdown Markdown renderer
markdown: kramdown
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
